---
title: "Week 3A - Global Baseline Estimate"
author: "Kristoff Oliphant"
date: "2026-02-11"
output: html_document
---

# Assignment 3A: Global Baseline Estimate

## Introduction

Last week I created a mini user-item rating dataset for 5 people to rate 6 movies from the year 2025-2026. For this assignment in week 3, I will continue where I left off and use the information I collected on movie ratings and implement a Global Baseline Estimate recommendation system in R.

## Planned Workflow

The way that I’ll approach my workflow this time is to use R again, pull the survey data I collected, and write the R code that makes a movie recommendation using the Global Baseline Estimate algorithm. Similar to the spreadsheet provided, I’ll pick one rater out of my group and assess what rating they would give for 1 of the 6 movies they have not watched.

## Anticipated Challenges

Some challenges I anticipate facing is to accurately utilize the Global Baseline Estimate algorithm. Additionally, I can tell that it needs to make sense with the mean movie rating, the selected movies rating relative to average, and lastly the user/rater of my choice rating relative to the average.
